### ISSUE TITLE
Add cpHastySpace support

### ISSUE THREAD

**Issue by konovod** [BlaXpirit/crystal-chipmunk#1]
Chipmunk 7.0 has multi-threaded implementation of solver. It also has additional performance on ARMs (makes use of NEON SIMD). Activating it is very simple: just call cpHastySpaceNew instead of cpSpaceNew and cpHastySpaceStep instead of cpSpaceStep (and perhaps set number of threads because NEON isn't very useful at a current state of Crystal). I think I can make a PR, but never tried it, so it will take some time.

**Comment by oprypin** [comment]
Last time I checked, I decided it's not worth the hassle because ARM was not supported by Crystal, basically there were no cases when it makes a difference. Now maybe there are such cases, you could try for a PR.
Really not sure how it should look. Maybe a subclass, maybe a boolean setting [like in pymunk](https://github.com/viblo/pymunk/blob/master/pymunk/space.py#L19)... or maybe just dropping *cpSpace* in favor of *cpHastySpace* would work?

**Comment by konovod** [comment]
boolean imho is the simplest variant - don't add overhead of virtual methods but still allows to use non-threaded implementation.

Actually PR doesn't looks so simple as you are using `cpSpaceInit` instead of `cpSpaceNew` and hasty space supports only `cpHastySpaceNew`.
This makes code simpler as you can send `self` instead of `@space`, but is it at all legitimate to call `cpSpaceInit` without calling `cpSpaceAlloc` before?

Also specs doesn't compile for me (crystal 0.20.3), yelling about problem with assert.

**Comment by oprypin** [comment]
This wrapper library relies on some implementation details of Chipmunk and lets Crystal do the memory allocation to avoid indirections.

So yeah, the lack of an `...Init` method is a problem. It means the wrapper for `HastySpace` would need to work differently than the rest.

As for the assert thing... A strange rename in standard library broke it.

```diff
diff --git a/src/spec_assert.cr b/src/spec_assert.cr                                                                                          
index de21bc6..a889d52 100644
--- a/src/spec_assert.cr
+++ b/src/spec_assert.cr
@@ -1,7 +1,7 @@
 require "spec"
 
 module Spec
-  module DSL
+  module Methods
     private def expected(a, s, b)
       String.build do |io|
         delta = s.size - "expected".size
```
